### ISSUE TITLE
Identical values for 'M_ratio_rS1' and 'M_ratio_rS2' in response conditional single subject fit

### ISSUE THREAD

**Issue by nwilming** [smfleming/HMM#7]
Hi,

firtst of all thanks for this really nice and very helpful package. 

I'm using this package for my own data and get some odd behavior. If I run the following code:

```
>> mcmc_params
mcmc_params = 
    response_conditional: 1
         estimate_dprime: 1
                 nchains: 3
                 nburnin: 1000
                nsamples: 10000
                   nthin: 1
              doparallel: 0
                     dic: 1
                   init0: [1x3 struct]

>> [nr_S1; nr_S2]

ans =

   208   674   236    10
    36   339   638   351

>> fit = fit_meta_d_mcmc(nr_S1, nr_S2, mcmc_params);
>> fit
fit = 

              d1: 1.3749
              c1: 0.0896
        t2ca_rS1: -1.3879
        t2ca_rS2: 1.5319
            mcmc: [1x1 struct]
      meta_d_rS1: 0.8120
      meta_d_rS2: 1.9425
     M_ratio_rS1: -0.5629  % <- !
     M_ratio_rS2: -0.5629 % <- !
     est_HR2_rS1: 0.2364
     obs_HR2_rS1: 0.2358
    est_FAR2_rS1: 0.0969
    obs_FAR2_rS1: 0.0960
     est_HR2_rS2: 0.3545
     obs_HR2_rS2: 0.3549
    est_FAR2_rS2: 0.0426
    obs_FAR2_rS2: 0.0407
```

The estimates for M_ratio_S1 & 2 are identical. Looking at lines 302 and following in fit_meta_d_mcmc suggests that there is a typo:

```
        fit.M_ratio_rS1 = mean(samples.meta_d_rS1(:)./d1_samples);
        fit.M_ratio_rS2 = mean(samples.meta_d_rS1(:)./d1_samples);  % Should be meta_d_rS2?
        fit.M_ratio_rS1 = mean(samples.meta_d_rS1(:) - d1_samples);
        fit.M_ratio_rS2 = mean(samples.meta_d_rS1(:) - d1_samples);  % Should be meta_d_rS2?
```
It would be great if you could confirm this.
Thanks!

**Comment by smfleming** [comment]
Hi Niklas,

Thanks for spotting this - you're right it's a typo.
I've now committed the correction. In general the single-subject code has received less attention since we started developing the group-level model, so please let me know if you find any other issues.

cheers

**Comment by nwilming** [comment]
Thanks for the super quick reply. Two more things:

 - Lines 303 and 304 should probably be `fit.M_diff_rS1/2 = ...`
 - setting `mcmc_params.dic = 0` yields an error because `stats.dic` does not exist.

**Comment by smfleming** [comment]
Thanks - will take a look and fix in due course

**Comment by smfleming** [comment]
These issues now fixed
